theme:
  name: torillic
  features: 
    - navigation.pathnavigation
site_name: Torillic
docs_dir: docs_src
site_dir: docs
nav:
  - Home: index.md
  - Example Statblocks: examples.md
markdown_extensions:
  - nl2br