site_name: Torillic MkDocs Example Wiki
# this is how you tell mkdocs to use torillic!
theme:
  name: torillic
  custom_dir: ../mkdocs_torillic
# choose a folder to build from and one to build to
docs_dir: docs_src
site_dir: docs
# tell mkdocs what links to put in the nav bar
# for bigger wikis, I suggest using something like the `literate-nav` plugin to generate this dynamically
nav:
  - Home: index.md
  - Bandit encounter:
    - Home: bandits/index.md
    - Bandit: bandits/Bandit.md
    - Bandit Captain: bandits/Bandit Captain.md
  - Dragon encounter:
    - Home: dragon/index.md
    - Adult Blue Dragon: dragon/Adult Blue Dragon.md
    - Cultist: dragon/Cultist.md
    - Kobold: dragon/Kobold.md
# tell mkdocs what to ignore (like those annoying junk files Google Drive makes)
exclude_docs: |
  desktop.ini
# tell mkdocs what markdown syntax to use
markdown_extensions:
  # "new line to break" - means it keeps single line breaks in the built html
  - nl2br