[project]
name = "sphinx-torillic"
version = "{{VERSION}}"
authors = [
    {name = "Todd Parsons", email = "todd.e.parsons@gmail.com"}
]

[project.entry-points."sphinx.html_themes"]
torillic = "torillic"

[tool.setuptools.package-data]
"*" = ["*.py", "*.png", "*.jpg", "*.css", "*.html", "*.conf"]