name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
     - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install packages
      run: |
        python -m pip install build twine
    - name: Check and update version
      id: version
      run: |
        python utils/publish.py
    - name: Build
      run: |
        python -m build mkdocs
    - name: Upload
      run: |
        twine upload mkdocs/dist/* --repository ${{steps.version.outputs.target}} -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
